# Generated by Django 3.2.13 on 2024-12-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitems_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='session_token',
            field=models.CharField(default='abc1', max_length=255),
        ),
    ]
