name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clona o repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configura o Docker Compose e sobe os containers
      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build -d

      # Aguarda os serviços estarem prontos
      - name: Wait for services to be ready
        run: |
          sleep 15  # Aguarda o banco e a aplicação iniciarem

      # Instala as dependências para testes
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Executa os testes com cobertura
      - name: Run tests with coverage
        run: |
          coverage run -m behave

      # Mostra o relatório de cobertura
      - name: Show test coverage report
        run: |
          coverage report --include="order/*"

      # Finaliza e remove os containers após os testes
      - name: Stop and remove Docker Compose services
        run: |
          docker-compose -f docker-compose.yml down
